import { Item } from "@/types";

export const mockItems: Item[] = [
  // Tools (8 items)
  {
    id: "1",
    name: "Power Drill Set",
    description: "Professional cordless drill with multiple bits and carrying case",
    category: "Tools",
    condition: "like-new",
    pricePerDay: 15,
    deposit: 100,
    location: "Downtown",
    distance: 2.3,
    images: ["https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&q=80"],
    owner: { id: "1", name: "John Doe", email: "john@example.com", rating: 4.8 },
    rating: 4.9,
    available: true,
  },
  {
    id: "5",
    name: "Ladder (Extension)",
    description: "20ft extension ladder for home projects",
    category: "Tools",
    condition: "good",
    pricePerDay: 10,
    deposit: 80,
    location: "Downtown",
    distance: 2.7,
    images: ["https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800&q=80"],
    owner: { id: "5", name: "David Brown", email: "david@example.com", rating: 4.7 },
    rating: 4.6,
    available: true,
  },
  {
    id: "24",
    name: "Lawn Mower",
    description: "Electric lawn mower with grass collection bag",
    category: "Tools",
    condition: "good",
    pricePerDay: 18,
    deposit: 150,
    location: "Westside",
    distance: 4.8,
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80"],
    owner: { id: "24", name: "Suresh Pillai", email: "suresh@example.com", rating: 4.6 },
    rating: 4.5,
    available: true,
  },
  {
    id: "25",
    name: "Circular Saw",
    description: "Heavy-duty circular saw for woodworking projects",
    category: "Tools",
    condition: "good",
    pricePerDay: 14,
    deposit: 120,
    location: "Midtown",
    distance: 3.4,
    images: ["https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=800&q=80"],
    owner: { id: "25", name: "Rajesh Kumar", email: "rajesh@example.com", rating: 4.8 },
    rating: 4.7,
    available: true,
  },
  {
    id: "26",
    name: "Angle Grinder",
    description: "Powerful angle grinder for cutting and grinding",
    category: "Tools",
    condition: "like-new",
    pricePerDay: 12,
    deposit: 90,
    location: "Eastside",
    distance: 2.9,
    images: ["https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&q=80"],
    owner: { id: "26", name: "Manoj Singh", email: "manoj@example.com", rating: 4.9 },
    rating: 4.8,
    available: true,
  },
  {
    id: "27",
    name: "Pressure Washer",
    description: "High-pressure washer for cleaning driveways and cars",
    category: "Tools",
    condition: "good",
    pricePerDay: 20,
    deposit: 180,
    location: "Downtown",
    distance: 1.7,
    images: ["https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&q=80"],
    owner: { id: "27", name: "Deepak Verma", email: "deepak@example.com", rating: 4.7 },
    rating: 4.6,
    available: true,
  },
  {
    id: "28",
    name: "Tool Box Set",
    description: "Complete tool box with 100+ pieces for home repairs",
    category: "Tools",
    condition: "like-new",
    pricePerDay: 16,
    deposit: 130,
    location: "Westside",
    distance: 3.8,
    images: ["https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=800&q=80"],
    owner: { id: "28", name: "Harish Patel", email: "harish@example.com", rating: 5.0 },
    rating: 4.9,
    available: true,
  },
  {
    id: "29",
    name: "Paint Sprayer",
    description: "Electric paint sprayer for walls and furniture",
    category: "Tools",
    condition: "good",
    pricePerDay: 15,
    deposit: 110,
    location: "Midtown",
    distance: 2.5,
    images: ["https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&q=80"],
    owner: { id: "29", name: "Vinod Kumar", email: "vinod@example.com", rating: 4.6 },
    rating: 4.5,
    available: true,
  },

  // Electronics (12 items)
  {
    id: "2",
    name: "Canon DSLR Camera",
    description: "Professional camera with 18-55mm lens, perfect for events",
    category: "Electronics",
    condition: "good",
    pricePerDay: 35,
    deposit: 500,
    location: "Midtown",
    distance: 3.1,
    images: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80"],
    owner: { id: "2", name: "Sarah Smith", email: "sarah@example.com", rating: 4.9 },
    rating: 4.7,
    available: true,
  },
  {
    id: "6",
    name: "Projector",
    description: "HD projector for movie nights and presentations",
    category: "Electronics",
    condition: "like-new",
    pricePerDay: 25,
    deposit: 300,
    location: "Midtown",
    distance: 3.5,
    images: ["https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&q=80"],
    owner: { id: "6", name: "Lisa Garcia", email: "lisa@example.com", rating: 4.8 },
    rating: 4.9,
    available: true,
  },
  {
    id: "15",
    name: "PlayStation 5",
    description: "Gaming console with 2 controllers and popular games",
    category: "Electronics",
    condition: "like-new",
    pricePerDay: 50,
    deposit: 800,
    location: "Midtown",
    distance: 2.9,
    images: ["https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&q=80"],
    owner: { id: "15", name: "Arjun Kapoor", email: "arjun@example.com", rating: 4.9 },
    rating: 5.0,
    available: true,
  },
  {
    id: "16",
    name: "Bluetooth Speaker",
    description: "Portable waterproof speaker with 20-hour battery life",
    category: "Electronics",
    condition: "good",
    pricePerDay: 8,
    deposit: 60,
    location: "Westside",
    distance: 3.8,
    images: ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80"],
    owner: { id: "16", name: "Kavya Iyer", email: "kavya@example.com", rating: 4.7 },
    rating: 4.6,
    available: true,
  },
  {
    id: "17",
    name: "Laptop (Dell XPS)",
    description: "High-performance laptop for work or gaming, i7 processor",
    category: "Electronics",
    condition: "good",
    pricePerDay: 40,
    deposit: 1000,
    location: "Downtown",
    distance: 1.6,
    images: ["https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&q=80"],
    owner: { id: "17", name: "Sanjay Desai", email: "sanjay@example.com", rating: 4.8 },
    rating: 4.7,
    available: true,
  },
  {
    id: "18",
    name: "Ring Light with Stand",
    description: "Professional LED ring light for photography and video calls",
    category: "Electronics",
    condition: "like-new",
    pricePerDay: 10,
    deposit: 80,
    location: "Eastside",
    distance: 2.4,
    images: ["https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80"],
    owner: { id: "18", name: "Pooja Nair", email: "pooja@example.com", rating: 4.9 },
    rating: 4.8,
    available: true,
  },
  {
    id: "19",
    name: "Drone with Camera",
    description: "4K camera drone with GPS and 30-min flight time",
    category: "Electronics",
    condition: "like-new",
    pricePerDay: 45,
    deposit: 700,
    location: "Midtown",
    distance: 3.3,
    images: ["https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800&q=80"],
    owner: { id: "19", name: "Karan Malhotra", email: "karan@example.com", rating: 5.0 },
    rating: 4.9,
    available: true,
  },
  {
    id: "30",
    name: "GoPro Action Camera",
    description: "Waterproof action camera with 4K video recording",
    category: "Electronics",
    condition: "like-new",
    pricePerDay: 30,
    deposit: 400,
    location: "Downtown",
    distance: 2.1,
    images: ["https://images.unsplash.com/photo-1519638399535-1b036603ac77?w=800&q=80"],
    owner: { id: "30", name: "Arun Sharma", email: "arun@example.com", rating: 4.8 },
    rating: 4.7,
    available: true,
  },
  {
    id: "31",
    name: "iPad Pro",
    description: "Latest iPad Pro with Apple Pencil for creative work",
    category: "Electronics",
    condition: "like-new",
    pricePerDay: 35,
    deposit: 800,
    location: "Midtown",
    distance: 2.8,
    images: ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80"],
    owner: { id: "31", name: "Meera Reddy", email: "meera@example.com", rating: 4.9 },
    rating: 4.8,
    available: true,
  },
  {
    id: "32",
    name: "Gaming Keyboard & Mouse",
    description: "RGB mechanical keyboard and gaming mouse combo",
    category: "Electronics",
    condition: "good",
    pricePerDay: 12,
    deposit: 100,
    location: "Eastside",
    distance: 3.2,
    images: ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80"],
    owner: { id: "32", name: "Rohit Gupta", email: "rohit@example.com", rating: 4.7 },
    rating: 4.6,
    available: true,
  },
  {
    id: "33",
    name: "Smart TV (55 inch)",
    description: "4K Smart TV with streaming apps built-in",
    category: "Electronics",
    condition: "like-new",
    pricePerDay: 40,
    deposit: 600,
    location: "Westside",
    distance: 4.1,
    images: ["https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&q=80"],
    owner: { id: "33", name: "Lakshmi Iyer", email: "lakshmi@example.com", rating: 5.0 },
    rating: 4.9,
    available: true,
  },
  {
    id: "34",
    name: "Soundbar System",
    description: "Premium soundbar with subwoofer for home theater",
    category: "Electronics",
    condition: "good",
    pricePerDay: 18,
    deposit: 250,
    location: "Downtown",
    distance: 1.9,
    images: ["https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&q=80"],
    owner: { id: "34", name: "Naveen Kumar", email: "naveen@example.com", rating: 4.8 },
    rating: 4.7,
    available: true,
  },

  // Kitchen (10 items)
  {
    id: "4",
    name: "Stand Mixer",
    description: "KitchenAid mixer with multiple attachments for baking",
    category: "Kitchen",
    condition: "like-new",
    pricePerDay: 12,
    deposit: 150,
    location: "Eastside",
    distance: 1.8,
    images: ["https://images.unsplash.com/photo-1578643463396-0997cb5328c1?w=800&q=80"],
    owner: { id: "4", name: "Emma Wilson", email: "emma@example.com", rating: 5.0 },
    rating: 5.0,
    available: true,
  },
  {
    id: "7",
    name: "Pressure Cooker (5L)",
    description: "Stainless steel pressure cooker, perfect for large family meals",
    category: "Kitchen",
    condition: "good",
    pricePerDay: 8,
    deposit: 80,
    location: "Downtown",
    distance: 1.5,
    images: ["https://images.unsplash.com/photo-1585515320310-259814833e62?w=800&q=80"],
    owner: { id: "7", name: "Priya Sharma", email: "priya@example.com", rating: 4.9 },
    rating: 4.8,
    available: true,
  },
  {
    id: "8",
    name: "Dinner Set (24 pieces)",
    description: "Elegant ceramic dinner set for parties and gatherings",
    category: "Kitchen",
    condition: "like-new",
    pricePerDay: 10,
    deposit: 120,
    location: "Eastside",
    distance: 2.8,
    images: ["https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=800&q=80"],
    owner: { id: "8", name: "Rahul Verma", email: "rahul@example.com", rating: 4.7 },
    rating: 4.6,
    available: true,
  },
  {
    id: "9",
    name: "Food Processor",
    description: "Multi-function food processor with chopping, grinding, and blending",
    category: "Kitchen",
    condition: "good",
    pricePerDay: 9,
    deposit: 100,
    location: "Midtown",
    distance: 3.2,
    images: ["https://images.unsplash.com/photo-1585515320310-259814833e62?w=800&q=80"],
    owner: { id: "9", name: "Anjali Patel", email: "anjali@example.com", rating: 5.0 },
    rating: 4.9,
    available: true,
  },
  {
    id: "10",
    name: "Coffee Maker",
    description: "Automatic drip coffee maker with thermal carafe",
    category: "Kitchen",
    condition: "like-new",
    pricePerDay: 7,
    deposit: 70,
    location: "Downtown",
    distance: 1.9,
    images: ["https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&q=80"],
    owner: { id: "10", name: "Vikram Singh", email: "vikram@example.com", rating: 4.8 },
    rating: 4.7,
    available: true,
  },
  {
    id: "35",
    name: "Air Fryer",
    description: "Large capacity air fryer for healthy cooking",
    category: "Kitchen",
    condition: "like-new",
    pricePerDay: 10,
    deposit: 120,
    location: "Midtown",
    distance: 2.6,
    images: ["https://images.unsplash.com/photo-1585515320310-259814833e62?w=800&q=80"],
    owner: { id: "35", name: "Swati Desai", email: "swati@example.com", rating: 4.9 },
    rating: 4.8,
    available: true,
  },
  {
    id: "36",
    name: "Blender (High-Speed)",
    description: "Professional blender for smoothies and soups",
    category: "Kitchen",
    condition: "good",
    pricePerDay: 8,
    deposit: 90,
    location: "Eastside",
    distance: 3.1,
    images: ["https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800&q=80"],
    owner: { id: "36", name: "Geeta Nair", email: "geeta@example.com", rating: 4.7 },
    rating: 4.6,
    available: true,
  },
  {
    id: "37",
    name: "Microwave Oven",
    description: "Convection microwave with grill function",
    category: "Kitchen",
    condition: "good",
    pricePerDay: 12,
    deposit: 150,
    location: "Downtown",
    distance: 2.3,
    images: ["https://images.unsplash.com/photo-1585515320310-259814833e62?w=800&q=80"],
    owner: { id: "37", name: "Sunil Mehta", email: "sunil@example.com", rating: 4.8 },
    rating: 4.7,
    available: true,
  },
  {
    id: "38",
    name: "Electric Kettle",
    description: "Fast-boiling electric kettle with temperature control",
    category: "Kitchen",
    condition: "like-new",
    pricePerDay: 5,
    deposit: 50,
    location: "Westside",
    distance: 3.7,
    images: ["https://images.unsplash.com/photo-1563822249366-3efbb5c8f9e6?w=800&q=80"],
    owner: { id: "38", name: "Rekha Singh", email: "rekha@example.com", rating: 4.9 },
    rating: 4.8,
    available: true,
  },
  {
    id: "39",
    name: "Induction Cooktop",
    description: "Portable induction cooktop with digital controls",
    category: "Kitchen",
    condition: "good",
    pricePerDay: 9,
    deposit: 100,
    location: "Midtown",
    distance: 2.9,
    images: ["https://images.unsplash.com/photo-1585515320310-259814833e62?w=800&q=80"],
    owner: { id: "39", name: "Ashok Kumar", email: "ashok@example.com", rating: 4.6 },
    rating: 4.5,
    available: true,
  },

  // Home Decor (8 items)
  {
    id: "11",
    name: "Decorative Wall Mirror",
    description: "Large ornate mirror with golden frame, perfect for living room",
    category: "Home Decor",
    condition: "like-new",
    pricePerDay: 15,
    deposit: 200,
    location: "Westside",
    distance: 4.1,
    images: ["https://images.unsplash.com/photo-1618220179428-22790b461013?w=800&q=80"],
    owner: { id: "11", name: "Neha Gupta", email: "neha@example.com", rating: 4.9 },
    rating: 4.8,
    available: true,
  },
  {
    id: "12",
    name: "Floor Lamp Set",
    description: "Modern standing lamps with adjustable brightness, set of 2",
    category: "Home Decor",
    condition: "good",
    pricePerDay: 12,
    deposit: 150,
    location: "Midtown",
    distance: 2.5,
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80"],
    owner: { id: "12", name: "Amit Kumar", email: "amit@example.com", rating: 4.6 },
    rating: 4.5,
    available: true,
  },
  {
    id: "13",
    name: "Artificial Plants Set",
    description: "Realistic artificial plants in decorative pots, set of 5",
    category: "Home Decor",
    condition: "like-new",
    pricePerDay: 6,
    deposit: 80,
    location: "Eastside",
    distance: 3.7,
    images: ["https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&q=80"],
    owner: { id: "13", name: "Sneha Reddy", email: "sneha@example.com", rating: 4.8 },
    rating: 4.7,
    available: true,
  },
  {
    id: "14",
    name: "Wall Art Canvas Set",
    description: "Abstract art canvas prints, set of 3 large pieces",
    category: "Home Decor",
    condition: "new",
    pricePerDay: 18,
    deposit: 250,
    location: "Downtown",
    distance: 2.1,
    images: ["https://images.unsplash.com/photo-1513519245088-0e12902e35ca?w=800&q=80"],
    owner: { id: "14", name: "Rohan Mehta", email: "rohan@example.com", rating: 5.0 },
    rating: 4.9,
    available: true,
  },
  {
    id: "40",
    name: "Decorative Cushions Set",
    description: "Colorful cushion covers with inserts, set of 6",
    category: "Home Decor",
    condition: "like-new",
    pricePerDay: 8,
    deposit: 100,
    location: "Eastside",
    distance: 2.7,
    images: ["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80"],
    owner: { id: "40", name: "Priyanka Joshi", email: "priyanka@example.com", rating: 4.8 },
    rating: 4.7,
    available: true,
  },
  {
    id: "41",
    name: "Table Runner & Placemats",
    description: "Elegant dining table runner with 6 placemats",
    category: "Home Decor",
    condition: "new",
    pricePerDay: 7,
    deposit: 90,
    location: "Midtown",
    distance: 3.3,
    images: ["https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800&q=80"],
    owner: { id: "41", name: "Kavita Sharma", email: "kavita@example.com", rating: 4.9 },
    rating: 4.8,
    available: true,
  },
  {
    id: "42",
    name: "Curtains Set",
    description: "Blackout curtains for bedroom, set of 2 panels",
    category: "Home Decor",
    condition: "good",
    pricePerDay: 10,
    deposit: 120,
    location: "Downtown",
    distance: 1.8,
    images: ["https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80"],
    owner: { id: "42", name: "Ramesh Patel", email: "ramesh@example.com", rating: 4.7 },
    rating: 4.6,
    available: true,
  },
  {
    id: "43",
    name: "Decorative Vases Set",
    description: "Modern ceramic vases in different sizes, set of 3",
    category: "Home Decor",
    condition: "like-new",
    pricePerDay: 9,
    deposit: 110,
    location: "Westside",
    distance: 4.2,
    images: ["https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=800&q=80"],
    owner: { id: "43", name: "Anita Desai", email: "anita@example.com", rating: 4.8 },
    rating: 4.7,
    available: true,
  },

  // Accessories (6 items)
  {
    id: "20",
    name: "Designer Handbag",
    description: "Luxury leather handbag, perfect for special occasions",
    category: "Accessories",
    condition: "like-new",
    pricePerDay: 20,
    deposit: 300,
    location: "Downtown",
    distance: 2.2,
    images: ["https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&q=80"],
    owner: { id: "20", name: "Riya Chopra", email: "riya@example.com", rating: 4.8 },
    rating: 4.7,
    available: true,
  },
  {
    id: "21",
    name: "Formal Suit (Men's)",
    description: "Premium 3-piece suit for weddings and formal events, size 40",
    category: "Accessories",
    condition: "like-new",
    pricePerDay: 25,
    deposit: 400,
    location: "Westside",
    distance: 4.2,
    images: ["https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&q=80"],
    owner: { id: "21", name: "Aditya Sharma", email: "aditya@example.com", rating: 4.9 },
    rating: 4.8,
    available: true,
  },
  {
    id: "22",
    name: "Party Jewelry Set",
    description: "Elegant artificial jewelry set with necklace, earrings, and bangles",
    category: "Accessories",
    condition: "new",
    pricePerDay: 15,
    deposit: 200,
    location: "Midtown",
    distance: 2.6,
    images: ["https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=80"],
    owner: { id: "22", name: "Divya Rao", email: "divya@example.com", rating: 5.0 },
    rating: 4.9,
    available: true,
  },
  {
    id: "23",
    name: "Travel Backpack (60L)",
    description: "Large hiking backpack with rain cover and multiple compartments",
    category: "Accessories",
    condition: "good",
    pricePerDay: 12,
    deposit: 150,
    location: "Eastside",
    distance: 3.1,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80"],
    owner: { id: "23", name: "Nikhil Joshi", email: "nikhil@example.com", rating: 4.7 },
    rating: 4.6,
    available: true,
  },
  {
    id: "44",
    name: "Designer Sunglasses",
    description: "Luxury branded sunglasses with UV protection",
    category: "Accessories",
    condition: "like-new",
    pricePerDay: 10,
    deposit: 150,
    location: "Downtown",
    distance: 2.4,
    images: ["https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&q=80"],
    owner: { id: "44", name: "Simran Kaur", email: "simran@example.com", rating: 4.8 },
    rating: 4.7,
    available: true,
  },
  {
    id: "45",
    name: "Leather Wallet Set",
    description: "Premium leather wallet and card holder set",
    category: "Accessories",
    condition: "new",
    pricePerDay: 8,
    deposit: 100,
    location: "Midtown",
    distance: 3.0,
    images: ["https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=80"],
    owner: { id: "45", name: "Tarun Malhotra", email: "tarun@example.com", rating: 4.9 },
    rating: 4.8,
    available: true,
  },

  // Sports Equipment (6 items)
  {
    id: "3",
    name: "Camping Tent (4-person)",
    description: "Waterproof tent perfect for weekend camping trips",
    category: "Sports Equipment",
    condition: "good",
    pricePerDay: 20,
    deposit: 250,
    location: "Westside",
    distance: 4.5,
    images: ["https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=800&q=80"],
    owner: { id: "3", name: "Mike Johnson", email: "mike@example.com", rating: 4.6 },
    rating: 4.8,
    available: true,
  },
  {
    id: "46",
    name: "Bicycle (Mountain)",
    description: "21-speed mountain bike for trails and city riding",
    category: "Sports Equipment",
    condition: "good",
    pricePerDay: 15,
    deposit: 300,
    location: "Downtown",
    distance: 2.0,
    images: ["https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?w=800&q=80"],
    owner: { id: "46", name: "Karthik Reddy", email: "karthik@example.com", rating: 4.8 },
    rating: 4.7,
    available: true,
  },
  {
    id: "47",
    name: "Yoga Mat & Blocks Set",
    description: "Premium yoga mat with blocks and strap",
    category: "Sports Equipment",
    condition: "like-new",
    pricePerDay: 6,
    deposit: 70,
    location: "Eastside",
    distance: 2.8,
    images: ["https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&q=80"],
    owner: { id: "47", name: "Nisha Gupta", email: "nisha@example.com", rating: 4.9 },
    rating: 4.8,
    available: true,
  },
  {
    id: "48",
    name: "Cricket Kit",
    description: "Complete cricket kit with bat, pads, gloves, and helmet",
    category: "Sports Equipment",
    condition: "good",
    pricePerDay: 18,
    deposit: 250,
    location: "Midtown",
    distance: 3.4,
    images: ["https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&q=80"],
    owner: { id: "48", name: "Vikas Sharma", email: "vikas@example.com", rating: 4.7 },
    rating: 4.6,
    available: true,
  },
  {
    id: "49",
    name: "Badminton Racket Set",
    description: "Professional badminton rackets with shuttlecocks, set of 2",
    category: "Sports Equipment",
    condition: "like-new",
    pricePerDay: 10,
    deposit: 120,
    location: "Westside",
    distance: 3.9,
    images: ["https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800&q=80"],
    owner: { id: "49", name: "Shalini Iyer", email: "shalini@example.com", rating: 4.8 },
    rating: 4.7,
    available: true,
  },
  {
    id: "50",
    name: "Dumbbells Set",
    description: "Adjustable dumbbells set (5-25kg) with stand",
    category: "Sports Equipment",
    condition: "good",
    pricePerDay: 12,
    deposit: 180,
    location: "Downtown",
    distance: 1.7,
    images: ["https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80"],
    owner: { id: "50", name: "Gaurav Singh", email: "gaurav@example.com", rating: 4.9 },
    rating: 4.8,
    available: true,
  },
];
